- nion/swift/LineGraphCanvasItem.py
This check would fail incorrectly when __entry_to_insert == 0.
```
if self.__foreign_legend_entry is not None and self.__entry_to_insert:
```
> Fix bug where foreign layers could not be inserted before index 0

- nion/swift/model/DocumentModel.py
This is required in order to be able to use these computations in sequences of spectrum images or 4D data sets. See also nion-software/niondata#15.
> Removed requirement '2d to 3d' from sequence integrate, trim and extract.

- nion/swift/LineGraphCanvasItem.py
The function that calculates the width of the y-axis tick labels widget was not aware of log-scale data. Since the data that gets drawn is the log of the actual data this width was too small for large values (for 10,000 it would calculate the width for a max value of 5). Now the system is aware of log-scaled data and calculates the width corretly.
> Make sure tick labels are not wider than drawing area for log line plots.

- nion/swift/LineGraphCanvasItem.py
- nion/swift/test/ImportExportManager_test.py
- nion/swift/test/LineGraphCanvasItem_test.py
Fixes #419.
Fixes #418.
Fixes #417.
Note: These changes depend on nion-software/nionutils#6
Now almost every kind of data should produce something sensible on log-line-plots. Especially data with negative values will not make the plot go crazy anymore.
Try and plot things like the following (and switch to log scale in the line plot):
```python
a = np.linspace(-5, 5, 10)
b = np.concatenate([a, -a, a, -a])
show(b)
c = np.ones(10)
c[::2] = -1
show(c)
```
Also check these plots out with only the stroke drawn.
It should all produce something useful.
> Line plot improvements

- nion/swift/LineGraphCanvasItem.py
- nion/swift/test/LineGraphCanvasItem_test.py
The test I added in the last commit fails for now, because it is fixed by nion-software/niondata#21.
The problem it highlights is that data containing nans will be handled improperly by the binning algorithm used for calculating the data of display panels that are fewer pixels wide than their data. One nan pixel can cause all pixels being nan after binning which will result in an empty line plot. Even thought the fix is in niondata, I still think this test should be here because it covers an important case for line plots.
> Line plot bugfixes

- nion/swift/model/Graphics.py
This fixes the position of the Fourier masks but not the shape of the ring mask.
> Fix center calculation in Fourier masks. Improves #566.

- .github/workflows/python-package.yml
- nion/swift/Application.py
- nion/swift/ScriptsDialog.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/Model.py
- nion/swift/model/Profile.py
- nion/swift/model/Schema.py
This prepares for expanding script item capabilities, such as
marking them as startup items or using them as buttons in dialogs.
Also type and code checking.
> Move script item persistent to profile. Clean up.

- nion/swift/Inspector.py
- nion/swift/LineGraphCanvasItem.py
- nion/swift/LinePlotCanvasItem.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/Model.py
- nion/swift/test/LineGraphCanvasItem_test.py
We could also consider changing the default stroke width to something a bit larger than the current 0.5. I'd say at least 1.0 would be good, maybe even 1.5 or 2. Right now, line plots are hardly visible most of the time because the line is so thin.
> Allow line plot stroke width to be changed. Add corresponding UI to Inspector.

- nion/swift/DataItemThumbnailWidget.py
- nion/swift/DisplayPanel.py
- nion/swift/DisplayScriptCanvasItem.py
- nion/swift/ImageCanvasItem.py
- nion/swift/Inspector.py
- nion/swift/LinePlotCanvasItem.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/DocumentModel.py
- nion/swift/test/ImageCanvasItem_test.py
Also will reorganize how adornments such as source/dependency items, collection/sequence/item pickers, and the scale marker are laid out.
> Provide collection/index controls in display panel

- docs/index.rst
- docs/release_notes.rst
- meta.yaml
- nion/swift/Application.py
- nion/swift/DisplayPanel.py
- nion/swift/Facade.py
- nion/swift/Inspector.py
- nion/swift/MimeTypes.py
- nion/swift/Workspace.py
- nion/swift/model/Connection.py
- nion/swift/model/DataGroup.py
- nion/swift/model/DataItem.py
- nion/swift/model/DataStructure.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/DocumentModel.py
- nion/swift/model/Graphics.py
- nion/swift/model/Persistence.py
- nion/swift/model/Project.py
- nion/swift/model/Symbolic.py
- nion/swift/test/DataGroup_test.py
- nion/swift/test/Persistence_test.py
- nion/swift/test/Storage_test.py
- setup.cfg
- Make unbindable protocol for use in unbinder. Eliminates a use of PersistentObject.
- Relax restriction on specifier to only require uuid.
- Simplify persistent object specifier so it is a basic wrapper around uuid.
- Version 0.16.1. Deselect panel. HDF5. Python 3.10.
> binder and release

- docs/basic_use.rst
Data processing section in the basic_use doc points the reader to Window > Computation for the Edit Computation panel, but I found this panel under Processing > Edit Computation instead in Swift 0.16.2. Updates to the doc to reflect this.
> Minor edit to the Data Processing section in the basic_use doc

- docs/user_guide.rst
Same new order without the heading reformatting. Disregard the previous pull request to restructure the user guide.
> Restructure User Guide Without Heading Formatting

- nion/swift/model/ImportExportManager.py
- nion/swift/test/ImportExportManager_test.py
- nion/swift/test/Symbolic_test.py
- Use scipy.fft instead of fftpack or numpy.fft.
- Use imageio.v3. Fix typing.
> imageio v3

- nion/swift/Application.py
- nion/swift/model/DocumentModel.py
- nion/swift/model/Symbolic.py
- nion/swift/test/Storage_test.py
- Fix utc date issue in test.
- Refactor to use exec/commit for script expression based computations too.
- Consolidate/combine computation queue item and computer merge objects into computations file.
- Merge computation queue item into computation for simplification.
- Put script and registered computation handlers into their own classes.
- Move executor functionality into ComputationExecutor (was minimal ComputeObject).
- Track computation executor in document model (full circle).
> computation errors

- nion/swift/Application.py
- nion/swift/ProjectPanel.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/FileStorageSystem.py
- nion/swift/model/Persistence.py
- nion/swift/model/Profile.py
- nion/swift/model/Project.py
- nion/swift/test/Storage_test.py
- nion/swift/test/TestContext.py
- Refactor file system classes to use interfaces. Prep for more refactoring.
- Refactor to move persistent_dict inside persistent_storage class.
- Simplify persistent storage interface / persistent object interaction.
- Continue refactor to reduce footprint of FileStorageSystem classes.
> file storage ds 2

- nion/swift/ActivityPanel.py
- nion/swift/DataPanel.py
- nion/swift/DisplayPanel.py
- nion/swift/DocumentController.py
- nion/swift/Facade.py
- nion/swift/HistogramPanel.py
- nion/swift/ImageCanvasItem.py
- nion/swift/Inspector.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/DocumentModel.py
- nion/swift/model/ImportExportManager.py
- nion/swift/model/Symbolic.py
- nion/swift/test/DataItem_test.py
- nion/swift/test/DisplayPanel_test.py
- nion/swift/test/Display_test.py
- nion/swift/test/DocumentController_test.py
- nion/swift/test/HistogramPanel_test.py
- nion/swift/test/Storage_test.py
- nion/swift/test/TestContext.py
- Simplify the display values available event handling.
- Simplify/consolidate display values stream in histogram processing.
- Eliminate redundant event (display_data_will_change_event).
- Fix display tracker leak in test.
- Fix #544. Simplify the display values pipeline and move it into its own thread.
> display values 2023 06 01

- nion/swift/resources/key_config.json
Adding an ellipse is freuqently needed when looking at the ronchigram camera, so a built-in keyboard shortcut would be usefeful.
> Add keyboard shortcut for 'Add ellipse graphic'.

- nion/swift/DocumentController.py
- nion/swift/ExportDialog.py
This is minor refactoring to isolate the actual code which exports the SVG file. Refactoring like this allows for tests to run SVG exports easily. This was part of my attempt to evaluate #874 which attempts to fix #591. However, I've decided to abandon #874 for now - and I'm planning to add more notes to #591.
References:
- #591 
- #874
> Refactor export svg to isolate actual file writing code.

- nion/swift/DocumentController.py
- nion/swift/ExportDialog.py
- **Refactored Export Dialog in Declarative Mode**
- **Do not pass redundant/unused 'parent_window'. Do not assign export dialog to unused variable.**
- **Clean up instance variables in export dialog and its model.**
- **Ensure that correct writer index is initialized.**
- **Change export filename building to use pathlib.**
- **Improve dialog box with default width and stretches.**
- **Ensure selected writer is saved in preferences when export is pressed.**
- **Fix issue where filename has a '.' (isodate on mac/linux).**
> ExportDialogDeclarative2

- nion/swift/ExportDialog.py
Following the discussions we had about the export results dialog, I have made a few changes:
- Added a scrollable area for when there are more exports than can fit on the screen
- Only display the dialog if there are some failed exports
> Updates to the export results dialog

- nion/swift/Thumbnails.py
See explanation in https://github.com/nion-software/nionswift/pull/1091
> Fix #1071. Make thumbnails dependent on display item graphic changes.

- nion/swift/ExportDialog.py
Made sure to use the Selected Directory, not the base directory from the Directory Dialog. This handles the case where the user has selected a folder in the Dialog but not entered the folder.  Additionally renamed the variable to be more explicit on the value that it contains.
> Use Selected Directory on Directory Dialog

- nion/swift/Application.py
- nion/swift/DocumentController.py
Moved the UI restore to a separate function from the standard Show event handler.  Added a call to that separate function only on first software load (creation of document controller) and removed it from the Show event handling. Functionality now should be it restores the last saved state only once, on software load. State during software running should be handled entirely by the windowing manager and not reloaded again.
> Changed UI state and geometry to only load at startup

- nion/swift/Inspector.py
Part of https://github.com/nion-software/nionswift/issues/1093
> Switching image display inspector section to declarative UI

- nion/swift/Workspace.py
- nion/swift/test/Workspace_test.py
- **Fix split issue by keeping splits when inserting new panel.**
- **Always split the target display panel rather than adding to row/column.**
This addresses #1104.
It also addresses a longstanding request to not make closing a display panel affect other display panels in same column/row, which was the case if you dragged a new item into a display panel such that it extended a row/column and then immediately closed it, in which case it would expand the remaining panels in a non-intuitive way. For instance, before this fix, make a 2x2, then drag an image to the left side of the top-left panel, then close the panel with the image. Resulting layout is not the original 2x2. In new version with this PR, it is. I think this is much more intuitive for arranging layouts, but may have unintended …
> Fix 1104 and only split panels two

- nion/swift/DataItemThumbnailWidget.py
- nion/swift/DataPanel.py
- nion/swift/DisplayCanvasItem.py
- nion/swift/DisplayPanel.py
- nion/swift/DisplayScriptCanvasItem.py
- nion/swift/ImageCanvasItem.py
- nion/swift/Inspector.py
- nion/swift/LineGraphCanvasItem.py
- nion/swift/LinePlotCanvasItem.py
- nion/swift/Panel.py
- nion/swift/test/DisplayPanel_test.py
- nion/swift/test/LineGraphCanvasItem_test.py
- **Refactor thumnail overlay to draw adornments separately from composition.**
- **Change HeaderCanvasItem to subclass AbstractCanvasItem to prepare for switch to composer.**
- **Refactor display panel overlay to draw adornments separately from composition.**
- **Eliminate repaint methods from display panel canvas items by moving into non-composition items.**
- **Consolidate layout into ImageAreaCanvasItem.**
- **Simplify axes and legend handling to avoid unnecessary measuring/sizing/updates.**
- **Make LineGraphLayer read-only. Preparation for compositor style drawing.**
- **Simplify line plot channel graphic to not be dependent on data.**
- **Simplify data panel again to thread-safe update instead of using main thread.**
I'm planning on merging these refactorings required for upcoming …
> 2024 09 10 pre compositor

- nion/swift/DataItemThumbnailWidget.py
- nion/swift/DisplayCanvasItem.py
- nion/swift/DisplayPanel.py
- nion/swift/DisplayScriptCanvasItem.py
- nion/swift/Facade.py
- nion/swift/HistogramPanel.py
- nion/swift/ImageCanvasItem.py
- nion/swift/Inspector.py
- nion/swift/LineGraphCanvasItem.py
- nion/swift/LinePlotCanvasItem.py
- nion/swift/Panel.py
- nion/swift/model/DataItem.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/DocumentModel.py
- nion/swift/model/Graphics.py
- nion/swift/model/Utility.py
- nion/swift/test/DisplayPanel_test.py
- nion/swift/test/LineGraphCanvasItem_test.py
- **Change the line plot canvas items to use compositor-style repainting.**
- **Separate each layer of line plot into its own canvas item.**
- **Convert remaining repaint canvas items to use composers.**
- **Convert image area layout to composer architecture.**
- **Ensure data item is not closed before running set_xdata.**
- **Eliminate unnecessary display update when removing display item.**
- **Improve handling of line graph layer composition.**
- **Update canvas items using batch update to avoid repainting partial states.**
- **Remove unnecessary invalidate calls.**
- **Change graphics to only draw if not closed.**
- **Fix typo in image zoom.**
- **Improve frame rate display to show actual rate of repainting.**
> 2024 09 10 compositor

- nion/swift/DataPanel.py
- nion/swift/model/DataItem.py
- nion/swift/model/DisplayItem.py
- nion/swift/resources/changes.json
How to test: these new stats show up in the data panel at the end of the shape line; and in the tool tips when hovering over items in the data panel.
> Add storage space to data panel info; add storage space/file-type to data item tool tip info.

- nion/swift/DocumentController.py
- nion/swift/ExportDialog.py
- nion/swift/Workspace.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/FileStorageSystem.py
- nion/swift/model/Graphics.py
- nion/swift/model/HDF5Handler.py
- nion/swift/model/ImportExportManager.py
- nion/swift/model/Persistence.py
- nion/swift/model/Profile.py
- nion/swift/model/Project.py
- nion/swift/model/Schema.py
- nion/swift/model/StorageHandler.py
- nion/swift/resources/changes.json
- nion/swift/test/DataPanel_test.py
- nion/swift/test/DocumentController_test.py
- nion/swift/test/ImportExportManager_test.py
- nion/swift/test/Storage_test.py
This adds a new import/export file format which can handle any internal data type and also includes the associated display. It is based on HDF5 and I chose the file extension "nhdf". The commits up until the last one are preparatory and can be reviewed in order. The last commit (bottom of the list below) is the actual introduction of the file format. This PR is not optimized or tested for performance. The writer implementation currently only exports a single display/data item; but the format itself supports multiple data and display items. The reader implements multiples already.
Testing this PR involves exporting any display item to a file and re-importing it into the same or another project. During import, all internal objects are assigned new uuid's so there is no conflict.
- **Change …
> Introduce nhdf file format based on HDF5 for import/export any display/data item

- nion/swift/Application.py
- nion/swift/ConsoleDialog.py
- nion/swift/DisplayPanel.py
- nion/swift/DocumentController.py
- nion/swift/model/DisplayItem.py
- nion/swift/model/Profile.py
- nion/swift/model/Project.py
- nion/swift/resources/menu_config.json
- nion/swift/test/DisplayItem_test.py
- nion/swift/test/DisplayPanel_test.py
- **Rename action_id for open project dialog.**
- **Remove duplicate import.**
- **Add a method to execute a list of application level commands.**
- **Add a switch project action, useful for testing.**
Console script, useful for testing. Switches repeatedly between last four projects.
```
app = api.application._application
project_uuids = [project_reference.project_uuid for project_reference in app._get_recent_project_references()[:4]]
commands = [("project.switch_project", {"project_uuid": project_uuid}) for project_uuid in project_uuids]
app.execute_command_list(commands, command_delay=2, repeat=10)
```
> Add switch project action and associated required machinery

- nion/swift/model/DisplayItem.py
- nion/swift/test/Display_test.py
The sample size was 200 and in no way could be representative of an
arbitrary complex valued image displayed in log-absolute. This was probably
done for perceived performance; but modern processors make the performance
issue minimal. So do not sample; just use the full range until a good
general sampling solution is implemented.
> Fix #1203. Eliminate use of data sampling to calculate complex display limits.

- nion/swift/EntityBrowser.py
- nion/swift/ProjectItemsDialog.py
- nion/swift/model/Schema.py
- **Change master detail handler to take sizing properties as parameter.**
- **Add support for add/remove buttons to master-detail browser.**
- **Refactor master detail browser to use simplified list based on property rather than mapping.**
- **Add tracking of parent entity in entities for compatibility with persistence framework.**
- **Expand entity custom class factory capability.**
- **Add ability to write entity to storage when inserted/removed.**
The master-detail browser is currently used in the project items dialog, which is a debugging dialog used to examine most objects in a project.
However, it is a generally useful UI element that can be used in future situations. Particularly, I'm working on a capability to add custom command buttons #926.
Additionally, the original main …
> improve master detail browser

- nion/swift/DataItemThumbnailWidget.py
- nion/swift/DataPanel.py
- nion/swift/Thumbnails.py
- nion/swift/model/DisplayItem.py
- nion/swift/test/DataItem_test.py
- nion/swift/test/DisplayPanel_test.py
- nion/swift/test/Storage_test.py
- nion/swift/test/Thumbnails_test.py
- **Simplify ThumbnailSource by using Python ref counting and merging with ThumbnailProcessor.**
- **Improve caching of thumbnail information.**
- **Disable list canvas item updating during display item list changes.**
See #1257. Not perfect, but significantly better than before.
Tested by creating a project with 1000 data items and switching to various choices in Collections panel.
> Improve performance of collections panel

- nion/swift/Application.py
- nion/swift/model/Feature.py
This can be used to allow users to enable/disable features that are still in development. It is a minimal implementation tested on upcoming command-palette and live-storage-space features.
> Add feature manager and associated preference panel.

- nion/swift/DisplayPanel.py
- nion/swift/FilterPanel.py
- nion/swift/Panel.py
- nion/swift/model/UISettings.py
- nion/swift/resources/changes.json
- setup.cfg
Adds highlighting when mouse over the title; and title middle truncation when
title is too long.
> Use canvas item layout to layout and render the display panel headers.

- nion/swift/model/Graphics.py
- nion/swift/model/Symbolic.py
- nion/swift/test/DataItem_test.py
- nion/swift/test/DataPanel_test.py
- nion/swift/test/DisplayPanel_test.py
- nion/swift/test/DocumentController_test.py
- nion/swift/test/DocumentModel_test.py
- nion/swift/test/Facade_test.py
- nion/swift/test/Inspector_test.py
- nion/swift/test/Storage_test.py
- nion/swift/test/Symbolic_test.py
- **Introduce Region objects to represent Graphics for computations.**
- **Introduce computation_value to bound item and pass it to computation instead of value.**
- **Pass Regions instead of Graphics to computations.**
- **Pass DataItemComputationValue instead of DataItem to computations.**
- **Pass DataStructureComputationValue to computations instead of directly passing DataStructure.**
- **Add computation_value to BoundList.**
- **Always pass data source to computation executor instead of passing data directly.**
- **Ensure computations are run in tests. Also additional test cleanup.**
This changes parameter passing to computations to only pass read-only parameters. This also changes parameters that used to pass xdata directly to computations to now pass data sources. Graphics and …
> Pass only read-only parameters to computation execute

- nion/swift/ImageCanvasItem.py
- nion/swift/LinePlotCanvasItem.py
- nion/swift/model/DisplayItem.py
- nion/swift/resources/changes.json
- nion/swift/test/DisplayPanel_test.py
- **Refactor displays to take display layer as object rather than dict.**
- **Pass display layer info to display canvas items.**
- **Use display data channel label if layer has no label.**
The first two commits are refactoring precursor to the last commit which makes line plot layers default to the data item name.
There are many edge cases and I expect to have a few follow-up PR's with bug fixes that get revealed during testing and/or features that go along with this change.
However, I think it's worthwhile to get this PR merged first to see what else needs to be fixed after testing and use.
> Fix 217. Use data item names for line plot layer names by default.

- nion/swift/ActivityPanel.py
- nion/swift/MetadataPanel.py
- nion/swift/resources/changes.json
- **Work-around for Qt layout issue on macOS.**
- **Fix issue with metadata panel not showing data. Also add note when target data item has no metadata.**
Metadata panel redraws in a thread for performance. The thread breaks its encapsulation to determine if it is visible, again, for performance. But drawing was not handling case where it was initially invisible and became visible. Now it redraws when becoming visible. Also other minor changes. Overall, this isn't the greatest implementation of threaded drawing, which could now be handled automatically. But I decided to avoid rewriting it since it was easiest to just "hack" this solution onto the current "hack". The painting-on-a-thread solution predates (and contirbutes to the ideas for) the more modern threaded canvas items.
This is a …
> fix 1363 metadata panel issues

- nion/swift/DataPanel.py
- nion/swift/DocumentController.py
This PR is a fix for #1370. Suggested testing procedure in that issue.
Please review the code. I will merge sometime after #1369. This PR (and any other PR today) will not pass tests without #1369, which includes an updated workspace split-enabled check after a change in nionui. If you want to try it out, checkout this on top of #1369.
> Ensure data panel selection is visible after revealing display items. Also notify if display item is filtered.

- nion/swift/DataPanel.py
- nion/swift/DocumentController.py
- nion/swift/Workspace.py
- nion/swift/test/DataPanel_test.py
- nion/swift/test/Workspace_test.py
This PR fixes #1353 and #1354. Basic integration tests, too.
- **Ensure files dropped on display panels appear in display panel.**
- **Handle data panel file dropping to import.**
This is a minor change. Reviewers can review to learn about code and be aware of the change. Planning to merge after a review approval or two days have passed.
Testing:
- drop external data file on display panel and confirm it is imported and displayed in the dropped panel
- drop external data file into data panel and confirm it is imported and selected in data panel
> fix 1353 drag and drop files

- nion/swift/DocumentController.py
This is a quick fix for:
- #1372
- #1373
Commits:
- [Improve naming of 'go to source/dependent' menu items.](https://github.com/nion-software/nionswift/pull/1374/commits/c5fa7ddc3e7834c4cb44fcdea6c5cacc4fa90c11)
- [Add items for composite display components to context menu.](https://github.com/nion-software/nionswift/pull/1374/commits/778ac3f00b6c354c752591c1b3b83f27694c31fe)
- [Use 'best' display item rather than assuming there is just one during reveals.](https://github.com/nion-software/nionswift/pull/1374/commits/1a99232f507f570d7a873abc3d259c89bff29dca)
- [Consolidate code, use action for reveals so they get logged.](https://github.com/nion-software/nionswift/pull/1374/commits/8bf55f6d804aff5c50865da38ad67385c25bb2e4)
Questions:
- Is the wording ok?
Review:
No urgency but I will …
> Improve naming of 'go to source/dependent' menu items, add 'reveal' component menu items

- nion/swift/Application.py
- nion/swift/GeneratorDialog.py
- nion/swift/model/FileStorageSystem.py
- nion/swift/model/HDF5Handler.py
- nion/swift/model/NDataHandler.py
- nion/swift/model/StorageHandler.py
- nion/swift/test/Storage_test.py
- **Improve error reporting when project can't be opened.**
- **Consolidate large format handling. Change file format to match changing data size.**
This changes behavior in the file storage system to automatically change the internal file format depending on the size of the data. A small data item stored as `.ndata` may be changed to `.h5` if the data size goes over 16MB.
Please review. The file storage system is not the cleanest code, but this change should be pretty clear that it tries to check the file type when the data changes. I'd like to merge this with or without reviews after two working days.
> Improve file format handling when data item data size changes

- nion/swift/model/DataItem.py
- nion/swift/model/Metadata.py
- nion/swift/test/Metadata_test.py
Please review. This is not urgent, but I plan to merge after two working days.
This fixes a regression [not sure if it ever worked 100%] and also cleans up setting of metadata values on `DataAndMetadata`. Also added tests to avoid breakage in the future.
> Fix regression where metadata value functions didn't work on dicts. Tests.

- nion/swift/DisplayPanel.py
Fixes #1306 
Added a check to see if the selected status has changed before resetting the style to ensure the current style is kept.
> Ensure styling of selected display panels remains consistent on clear

- nion/swift/LineGraphCanvasItem.py
- nion/swift/model/DisplayItem.py
- **Change line plot to not draw returns to baseline on strokes.**
- **Ensure display data channel display values initially get calculated.**
Please review these two commits. The first (don't draw returns to baseline) change how drawing looks on the ends of segments #1443. The second fixes an issue where sometimes line plots would not draw initially #1418. I would like to merge them after a day. See #1443 for drawing notes.
> line plot tweaks

- nion/swift/DocumentController.py
- nion/swift/ProjectPanel.py
This adds the missing ability to rename a data group. It requires the recent changes in `nionui`. The basic functionality is to click on a data group in the Collections panel, and either hit return or double click the item to change the name. The resulting pop-up dialog should be able to copy/paste/cut/select-all. The pop-up dialog should immediately respond to typing, i.e. not require any additional focus clicks; and should also respond to return to accept and escape to cancel.
Please review with the consideration that this is an acceptable but probably incomplete solution to #1463. I would suggest reviewing to ensure it is working as expected. I would also suggest testing this pop-up in varying situations including using return/escape, switching out of the application, exiting the …
> Add ability to rename data group by hitting return or double clicking on list item.

- nion/swift/model/DocumentModel.py
- nion/swift/test/DocumentModel_test.py
> Change title of duplicated items to 'Duplicate', was 'Copy'.

- nion/swift/model/DisplayItem.py
- nion/swift/test/InfoPanel_test.py
Fixes #1600.
Please review.
NOTE: This requires https://github.com/nion-software/niondata/pull/69 to work.
> Fix #1600. Offset position by 1/2 pixel for Fourier space info panel coordinates. Add test.

- nion/swift/model/Utility.py
There are a few Windows systems where overwriting a file isn't possible a short time after closing it. This handles that situation.
> Make atomic file writing more robust by using retries.
