docs/release_notes.rst, nion/swift/model/DocumentModel.py, nion/swift/test/DocumentModel_test.py
This is in preparation for and updated `MultiAcquire` that will allow users to acquire sequences of spectrum images.
=> Add support for running 'pick' on sequences of spectrum images.

nion/swift/LinePlotCanvasItem.py
Fixes point 3 in my comment to https://github.com/nion-software/nionswift/issues/37#issuecomment-619353474:
>     3. Again specific to interval regions: Very often you create one if you just click on the image which has width 0 or something very small. I would suggest that we introduce a minimum width under which intervals don't get created by simply dragging over a line plot.
=> Introduce a distance threshold for creating a new interval on line plots.

nion/swift/model/ImportExportManager.py, nion/swift/test/ImportExportManager_test.py
=> Fix import and export of data_items with 'large_format' flag. Add test.

nion/swift/DataItemThumbnailWidget.py, nion/swift/DataPanel.py, nion/swift/DisplayPanel.py, nion/swift/HistogramPanel.py, nion/swift/Inspector.py, nion/swift/Panel.py, nion/swift/Thumbnails.py, nion/swift/model/DocumentModel.py, nion/swift/model/Profile.py, nion/swift/test/Connection_test.py, nion/swift/test/DataItem_test.py, nion/swift/test/DisplayItem_test.py, nion/swift/test/DisplayPanel_test.py, nion/swift/test/DocumentModel_test.py, nion/swift/test/HardwareSource_test.py, nion/swift/test/HistogramPanel_test.py, nion/swift/test/Inspector_test.py, nion/swift/test/Profile_test.py, nion/swift/test/Project_test.py, nion/swift/test/Storage_test.py, nion/swift/test/Symbolic_test.py, nion/swift/test/TestContext.py, nion/swift/test/Thumbnails_test.py, setup.cfg
- Ensure value streams implement about_to_delete rather than close.
- Fix and test for numerous ref counting errors.
=> fix ref counting

docs/data_management.rst, docs/display_panels.rst, docs/graphics.rst, docs/processing.rst, docs/requirements.txt, docs/user_interface.rst
- Bump to numpy 1.21.3 for testing.
- Fix issues displaying adjusted (equalized, gamma, etc.) images. Tests.
- WIP: Describe the rest of the user interface in docs.
=> doc update1

nion/swift/DisplayPanel.py, nion/swift/LinePlotCanvasItem.py, nion/swift/test/DisplayPanel_test.py
- Consolidate unnecessary code.
- Fixed #758. Also fixed problem constructing composite line plots. Test.
=> fix 758 line plot composite

docs/index.rst, docs/release_notes.rst, meta.yaml, nion/swift/Application.py, setup.cfg, test-requirements.txt
- Update release notes.
- Version 0.16.0. Reliability. Move hardware source. Activity/notification.
=> release 16

.github/workflows/python-package.yml, nion/swift/HistogramPanel.py, nion/swift/model/FileStorageSystem.py, nion/swift/model/Project.py
- Fix minor typing issue. Update mypy to 942.
- Record file loading errors and report more concisely.
=> file load error

nion/swift/model/ImportExportManager.py, nion/swift/test/ImportExportManager_test.py
To prepare for additional types being added into the ImportExportManager, this change adds in
functionality to load and save images of the WebP format.
Testing code is updated to reflect this change in addition.
=> Added WebP image compatibility into the ImportExportManager Components

nion/swift/Inspector.py
This resolves #981 (second half of the implementation, the first one being in niondata: nion-software/niondata#52)
=> Add the option to display the phase of a complex array

nion/swift/DocumentController.py, nion/swift/ExportDialog.py
@Ion-e This fixes the issue with context menus after exporting to SVG.
=> Fix issue where display item snapshot was not closed.

nion/swift/Inspector.py
Moving the sequence inspector section over to declarative UI
=> 1093 sequence inspector section

nion/swift/ExportDialog.py
Hi @cmeyer I have updated all of my pull requests with changes and fork syncing issues however due to architectural changes this PR will need to go in first so can we work this one through first then i will convert the rest from draft.
=> Fix SVG precision bug - Updated

nion/swift/model/ColorMaps.py, nion/swift/resources/changes.json
I just need one reviewer for this...
=> Fix #707. Add ability to register color tables from packages.

nion/swift/Inspector.py, nion/swift/model/DisplayItem.py, nion/swift/test/DisplayItem_test.py, nion/swift/test/Inspector_test.py
Please review. This is part of the SVG changes.
=> Extend calibrated calibrations tests and fix bugs; restore part of inspector calibration code.

nion/swift/model/DisplayItem.py, nion/swift/test/InfoPanel_test.py
Co-authored-by: lisham2000 <luke.isham@bruker.com>
=> Fix position ordering issue in get_display_position_as_data_position.

nion/swift/DataPanel.py, nion/swift/DocumentController.py, nion/swift/ProjectPanel.py, nion/swift/model/DataItem.py, nion/swift/model/DisplayItem.py
- **Simplify collection count observation by using value stream.**
- **Rename CollectionDisplayItemCounter to CollectionInfoController and clean-up.**
- **Move collection info management to document controller.**
- **Use collection info in data panel too.**
- **Minor optimizations for data panel filtering.**
=> improve collection panel

.github/workflows/python-package.yml, nion/swift/test/DisplayPanel_test.py, pyproject.toml, test-requirements.txt
- **Make tests compatible with pytest; add pytest options to pyproject.toml.**
- **Update build action to use reusable workflow.**
=> reusable workflow

nion/swift/DisplayPanel.py, nion/swift/DocumentController.py, nion/swift/ImageCanvasItem.py, nion/swift/LinePlotCanvasItem.py, nion/swift/model/DocumentModel.py, nion/swift/model/Graphics.py, nion/swift/model/Symbolic.py, nion/swift/resources/changes.json, nion/swift/test/Graphics_test.py
- **Add graphic attribute testing to replace isinstance use.**
- **Fix #1238. Add line profile automatically computation when pasting line profile graphic.**
Note: I inadvertently included a maintenance commit (graphic attribute testing). Both are reviewable. I plan to merge these Jan 24.
=> copy paste line profile

nion/swift/DataPanel.py, nion/swift/test/DataPanel_test.py
Any reviews welcome. Otherwise merging soon.
=> Fix #1324. Inspector now shows selected data panel item.

nion/swift/DisplayCanvasItem.py, nion/swift/DisplayPanel.py, nion/swift/DisplayScriptCanvasItem.py, nion/swift/ImageCanvasItem.py, nion/swift/LineGraphCanvasItem.py, nion/swift/LinePlotCanvasItem.py, nion/swift/model/Graphics.py, nion/swift/resources/changes.json
This PR makes unfocused graphics draw in a different style.
=> Fix #1331. Draw graphics in alternate style when unfocused.

nion/swift/Application.py, nion/swift/ComputationPanel.py, nion/swift/DisplayPanel.py, nion/swift/DocumentController.py, nion/swift/Inspector.py, nion/swift/RecorderPanel.py, nion/swift/Undo.py, nion/swift/Workspace.py
- **Modify undo commands to override _perform instead of perform.**
- **Add minimal command logger for debugging crashes.**
=> 2025 02 19 command logger

nion/swift/Facade.py, nion/swift/model/Symbolic.py
- **Add computation.get_input for use in plug-in computations.**
- **Add structure_type to Facade.DataStructure for use in plug-ins.**
- **Add methods to access data item and graphic inputs.**
=> Improve API to avoid accessing internal objects

nion/swift/DocumentController.py, nion/swift/model/DocumentModel.py, nion/swift/model/Feature.py, nion/swift/model/Symbolic.py, nion/swift/test/Symbolic_test.py
- **Improve feature manager to handle enabled-by-default features.**
- **Add asynchronous (threaded) computation capability.**
=> Fix #304. Asynchronous (threaded) computations

nion/swift/DocumentController.py, nion/swift/test/DataPanel_test.py
Linked Issue #1378.
This PR fixes discrepancies between what is drawn as selected in the data panel, the actual selection indexes, and the selected display items. Also adds a messy regression test to test this specific case.
Reviews are appreciated. The key code is documented in comments. Other code is related refactoring. I plan to merge this after getting an approval review or after two working days.
Regarding testing: this can be tested against the instructions in #1378. There may. be other lurking focus issues similar to this. But I did do a reasonably comprehensive search for similar cases and did not find any.
=> Fix issue where selected data items not updated for all selection mutations. Test.

nion/swift/Panel.py, nion/swift/Thumbnails.py
- **Pass on begin_changes_event from ThreadSafeListModel to match end_changes_event.**
- **Refactor thumbnail source to avoid costly 'clean' for garbage collection.**
This improves performance of the data panel, particularly filtering. There are still outstanding performance issues.
Linked issue https://github.com/nion-software/nionswift/issues/1387
Please review. I plan to merge this within two working days.
=> Improve performance of data panel filtering

nion/swift/model/DocumentModel.py
Please review for education and bug spotting. I'm merging this already to continue acquisition testing, but still open to reviews.
This fixes a race condition where acquisition sets pending data from a thread but the data item has already been removed from the project. It could show up during acquisition test dashboard when items deleted quickly after acquisition.
=> Fix race condition when setting pending data after potentially removed from project.

nion/swift/model/Symbolic.py, nion/swift/test/Symbolic_test.py
This is a low level to reduce unnecessary computations, e.g. recomputing line plot when mask on source display item changes. Please review - I'd like to merge this after two days if no one takes a look. It's low priority, but works to make the computation system more efficient.
=> Fix #1428. Reduce unnecessary computation recomputes on unrelated changes.

nion/swift/model/DisplayItem.py, nion/swift/resources/changes.json, nion/swift/test/DisplayItem_test.py
Fixes #1590.
Please review code, integrated test, and test against original issue.
=> Fix calibration issues in display adjustment processors. Add tests. Fixes #1590.
